---
version: "3.8"

services:
  discord-alertmanager:
    image: ghcr.io/lrstanley/discord-alertmanager:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - DISCORD_TOKEN=REPLACE_ME
      - ALERTMANAGER_URL=http://localhost:9093
      # if basic auth is being used.
      # - ALERTMANAGER_USERNAME=REPLACE_ME
      # - ALERTMANAGER_PASSWORD=REPLACE_ME
